config/routes.rb
Ticketer::Application.routes.draw do

  scope(path_names: { new: 'novo', show: 'visualizar', edit: 'editar' } ) do

    resources :locals,         path: 'locais'
    resources :call_histories, path: 'historico_de_chamadas'
    resources :guidances,      path: 'orientacoes'
    resources :tickets,        path: 'senhas'
    resources :statuses,       path: 'status'
    resources :status_tickets, path: 'status_de_senha'
    resources :printers,       path: 'impressoras'

    resources :ticket_type_groups, path: 'grupos_tipo_de_senha' do
      resources :ticket_types,     path: 'tipos_de_senha'
    end

    resources :places, path: 'localidades' do

      get 'home', path: 'lista_de_guiches'

      resources :tickets, path: 'senhas'

      resources :reports, path: 'relatorios', only: :index do
        get 'tickets_per_day',                  path: 'senhas_por_dia',                      on: :collection
        get 'tickets_per_month',                path: 'senhas_por_mes',                      on: :collection
        get 'attendances_by_days_per_wicket',   path: 'atendimentos_por_dia_por_guiche',     on: :collection
        get 'attendances_by_wickets_per_day',   path: 'atendimentos_por_guiche_por_dia',     on: :collection
        get 'attendances_by_wickets_per_month', path: 'atendimentos_por_guiche_por_mes',     on: :collection
        get 'waiting_time_by_wicket',           path: 'tempo_de_espera_por_guiche',          on: :collection
        get 'waiting_time_by_day_per_wicket',   path: 'tempo_de_espera_por_dia_por_guiche',  on: :collection
        get 'waiting_time_by_wicket_per_month', path: 'tempo_de_espera_por_guiche_por_mes',  on: :collection
        get 'waiting_time_by_client',           path: 'tempo_de_espera_por_cliente',         on: :collection
        get 'waiting_time_by_client_per_month', path: 'tempo_de_espera_por_cliente_por_mes', on: :collection
        get 'waiting_time_by_month_per_wicket', path: 'tempo_de_espera_por_mes_por_guiche',  on: :collection
        get 'attendances_by_month_per_wicket',  path: 'atendimentos_por_mes_por_guiche',     on: :collection
      end

      resources :panels, path: 'paineis' do
        get 'tickets',   path: 'senhas'
      end

      resources :wickets,     path: 'guiches' do
        get 'tickets',        path: 'senhas'
        get 'call_next',      path: 'chamar_proximo'
        get 'call_ticket',    path: 'chamar_senha'
        put 'recall',         path: 'rechamar'
        put 'attend',         path: 'atender'
        put 'put_waiting',    path: 'por_em_espera'
        put 'back_available', path: 'tornar_disponivel'
        put 'examine',        path: 'examinar'
        delete 'cancel',      path: 'cancelar'
      end

      resources :totems do
        get 'ticket_type_groups', path: 'grupos_tipo_senha'
        get 'generate_ticket',    path: 'gerar_senha'

        resources :ticket_type_groups do
          get 'generate_ticket', path: 'gerar_senha'
        end
      end

    end
  end

  match 'main' => "home#main", as: "main"
  match 'localidades' => "places#home", as: "home"
  match 'logout' => "session#logout"
  root to: 'home#index'

end

app/models/totem.rb
class Totem < ActiveRecord::Base
  extend FriendlyId
  
  friendly_id :value, use: :slugged

  #String :value
  #String :ip
  #String :user

  belongs_to :status
  belongs_to :place
  belongs_to :printer
  has_many :tickets

  validates :value, :ip, :user, :status, :place, :printer, :presence => true

  validates :value,
    :length => { :in => 1..80 },
    :uniqueness => { :case_sensitive => false, :scope => :place_id },
    :allow_blank => true

  validates :ip,
    :length => { :in => 1..15 },
    :uniqueness => true,
    :format => { :with => /^((?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))(?![\d])$/ },
    :allow_blank => true

end

app/controllers/totems_controller.rb
class TotemsController < ApplicationController
  prepend_before_filter :generate_ticket_must_pass, :only => :generate_ticket

  def index
    @place = Place.find(params[:place_id])
    @totems = Totem.where(:place_id => @place.id).order( "value ASC" )
    respond_with(@totems)
  end

  def show
    @totem = Totem.find(params[:id])
    @place = Place.find(params[:place_id])
    respond_with(@totem)
  end

  def new
    @totem = Totem.new( :status => Status.active )
    @place = Place.find(params[:place_id])
    @printers = Printer.order(:name)
    respond_with(@totem)
  end

  def edit
    @totem = Totem.find(params[:id])
    @place = Place.find(params[:place_id])
    @printers = Printer.order(:name)
  end

  def create
    @totem = Totem.new(params[:totem])
    @place = Place.find(params[:place_id])
    @totem.user = "user test"
    flash[:notice] = 'Totem was successfully created.' if @totem.save
    respond_with(@totem, location: place_totem_url(@place, @totem))
  end

  def update
    @totem = Totem.find(params[:id])
    @place = Place.find(params[:place_id])
    flash[:notice] = 'Totem was successfully updated.' if @totem.update_attributes(params[:totem])
    respond_with(@totem, location: place_totem_url(@place, @totem))
  end

  def generate_ticket
    @place = Place.find(params[:place_id])
    @ticket_type_groups = @place.ticket_type_groups.order(:value)
    respond_with(@ticket_type_groups) do |format|
      format.html { render :layout => 'application-totem' }
    end
  end

  def ticket_type_groups
    @place = Place.find(params[:place_id])
    @ticket_type_groups = @place.ticket_type_groups.order(:value)
    respond_with(@ticket_type_groups) do |format|
      format.html { render :layout => 'application-totem' }
    end
  end

  private

  #Necessary to CAS authentication bypass
  def generate_ticket_must_pass
    @it_is_required = true
  end
  def require_been_loged?
    @it_is_required
  end
end

app/views/totems/_form.html.erb
<%= form_for([@place, @totem]) do |f| %>
  <%= f.hidden_field :place_id, :value => @place.id %>
  <% if @totem.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @totem.errors.full_messages.each do |msg| %>
        <li class="form-msg-error"><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="grid-12-12">
    <%= f.label :value, :class => "form-lbl form-req" %>
    <%= f.text_field :value, :maxlength => 80, :size => 30, :class => "form-txt form-small", :disabled => disabled %>
  </div>
  <div class="grid-12-12">
    <%= f.label :ip, :class => "form-lbl form-req"  %>
    <%= f.text_field :ip, :maxlength => 15, :class => "form-txt form-small", :disabled => disabled %>
  </div>
  <div class="grid-12-12">
    <%= f.label :printer, :class => "form-lbl form-req" %>
    <% if @totem && @totem.printer_id && disabled %>
      <input type="text" value="<%= @totem.printer.name %>" disabled="disabled" class="form-txt form-small" />
    <% elsif %>
      <%= f.collection_select( :printer_id, @printers, :id, :name, { :prompt => true }, :class => "form-small", :disabled => disabled ) %>
    <% end %>
  </div>
  <div class="grid-12-12">
    <%= f.label :status, :class => "form-lbl form-req" %>
    <ul class="form-list-rdo">
      <% Status.all.each do |status| %>
        <li>
          <%= f.radio_button :status_id, status.id , :disabled => disabled  %> 
          <%= f.label status.value, :class => "form-lbl" %>
        </li>
      <% end %>
  </div>

  <% unless disabled %>
    <div class="grid-7-12 field-button field-clear">
      <%= f.submit :class => "button form-right medium" %>
    </div>
  <% end %>
<% end %>

app/views/totems/edit.html.erb
<div class="form">
  <fieldset>
    <legend><%= t('model.totem.editing') %></legend>
    <%= render :partial => 'form', :locals => {:disabled => false } %>
  </fieldset>
</div>
<div class="buttons-nav">
  <%= link_to t('model.show'), place_totem_path(@totem.place, @totem), :class => "button medium"  %> 
  <%= link_to t('model.back'), place_totems_path(@totem.place) , :class => "button medium" %>
</div>

app/views/totems/generate_ticket.html.erb
<div class="totem">
<%= form_for( Ticket.new ) do |f| %>
  <%= f.hidden_field :ticket_type_id %>
  <%= f.hidden_field :totem_id, :value => params[:totem_id] %>
  <%= f.hidden_field :place_id, :value => params[:place_id] %>
  <% @ticket_type_groups.each do |ticket_type_group| %>
    <div class="ticket_type_group"><%= ticket_type_group.value %></div>
    <% ticket_type_group.ticket_types.where(:status_id => Status.active.id).each do |ticket_type| %>
      <div id="<%= ticket_type.id %>" class="ticket_type generate"><span><%= ticket_type.value %></span></div>
    <% end %>
  <% end %>
<% end %>
</div>

<%= javascript_include_tag  'facebox', 'facebox-plugin', 'jquery.jclock' %>
<script type="text/javascript" charset="utf-8">
   jQuery.clock();
   jQuery( 'div.generate' ).click( function() {
    $.blockScreen();
    jQuery( '#ticket_ticket_type_id' ).val( this.id );
    param = jQuery( '#new_ticket' ).serialize();
    jQuery.ajax({
      url: "/senhas",
      type: "post",
      data: param,
      dataType: 'json',
      success: function(data){
        $.displayScreen()
        jQuery.facebox.new( '<div><h3 style="text-align: center;">HOSPITAL SANTA IZABEL</h3><br/><h4 style="text-align: center;">' + data.place_value + '</h4><br/><h1 style="text-align: center; color: red; font-weight: bold;">' + data.value + '</h1><br/><b>Tipo:</b> ' + data.ticket_type_value + '<br/><b>Data:</b> ' + data.created_at_formatted + '</div>').fadeOutIn(3000);
      }
    });
  });
</script>
</div>

app/views/totems/index.html.erb
<div class="form">
  <div class="place-spot">
    <%= "#{t('model.place.name')}: " %><b><%= @place.value %></b>
  </div>
  <div class="search">
    <input type="text" value="search" id="search"/>
    <%= link_to image_tag("form/search.png") + t('application.search') , "#", :class => "button medium"%>
  </div>
  <table>
    <tr>
      <th><%= t('model.totem.name').pluralize %></th>
      <th><%= t('model.totem.ip') %></th>
      <th><%= t('model.printer.name') %></th>
      <th><%= t('model.status.name') %></th>
      <th colspan="4" class="options"><%= t("application.options") %></th>
    </tr>
    <% @totems.each do |totem| %>
      <tr class="row">
        <td width="50%"><%= totem.value %></td>
        <td width="20%"><%= totem.ip %></td>
        <td width="20%"><%= totem.printer ? totem.printer.name : '' %></td>
        <td width="10%"><%= totem.active?  ? t('model.status.active') : t('model.status.inactive') %></td>
        <td>
          <%= link_to image_tag("form/search.gif"), place_totem_path(totem.place, totem), :title => t('model.show') %>
        </td>
        <td>
          <%= link_to image_tag("form/edit.gif"), edit_place_totem_path(totem.place, totem), :title => t('model.edit') %>
        </td>
        <td>
	    <% if @place.ticket_type_groups.size > 2 %>
          <%= link_to image_tag("form/note.gif"), place_totem_ticket_type_groups_path(totem.place, totem), :title => t('model.generate') %>
        <% else %>
          <%= link_to image_tag("form/note.gif"), place_totem_generate_ticket_path(totem.place, totem), :title => t('model.generate') %>
        <% end %>
        </td>
        <td>
			<%= link_to image_tag("form/trash.gif"), place_totem_path(totem.place, totem), :confirm => t('model.destroy_question'), :method => :delete, :title => t('model.destroy') %>
		</td>
      </tr>
    <% end %>
  </table>
</div>
<div class="buttons-nav">
  <%= link_to t('model.totem.new'), new_place_totem_path(@place),:class => "button medium" %> 
  <%= link_to t('model.place.back'), places_path, :class => "button medium" %>
</div>

app/views/totems/new.html.erb
<div class="form">
  <fieldset>
    <legend><%= t('model.totem.new') %></legend>
    <%= render :partial => 'form', :locals => {:disabled => false } %>
  </fieldset>
</div>
<div class="buttons-nav">
  <%= link_to t('model.back'), place_totems_path(@place), :class => "button medium"  %>
</div>

app/views/totems/show.html.erb
<div class="form">
  <fieldset>
    <legend><%= t('model.totem.name') %></legend>
    <% if notice %>
      <span class="form-msg-success"><%= notice %></span>
    <% end %>
    <%= render :partial => 'form', :locals => {:disabled => true } %>
  </fieldset>
</div>

<div class="buttons-nav">
  <%= link_to t('model.edit'), edit_place_totem_path(@totem.place, @totem), :class => "button medium"  %> 
  <%= link_to t('model.back'), place_totems_path(@totem.place), :class => "button medium"  %>
</div>

app/views/totems/ticket_type_groups.html.erb
<div class="totem_group">
<%= form_for( Ticket.new ) do |f| %>
  <%= f.hidden_field :totem_id, :value => params[:totem_id] %>
  <%= f.hidden_field :place_id, :value => params[:place_id] %>
  <% @ticket_type_groups.each do |ticket_type_group| %>
    <%= link_to place_totem_ticket_type_group_generate_ticket_path(params[:place_id], params[:totem_id], ticket_type_group.id) do %>
      <div class="ticket_type_groups generate"><span><%= ticket_type_group.value %></span></div>
    <% end %>
  <% end %>
<% end %>
</div>

<%= javascript_include_tag 'jquery.jclock' %>
</div>