config/routes.rb
Ticketer::Application.routes.draw do

  scope(path_names: { new: 'novo', show: 'visualizar', edit: 'editar' } ) do

    resources :locals,         path: 'locais'
    resources :call_histories, path: 'historico_de_chamadas'
    resources :guidances,      path: 'orientacoes'
    resources :tickets,        path: 'senhas'
    resources :statuses,       path: 'status'
    resources :status_tickets, path: 'status_de_senha'
    resources :printers,       path: 'impressoras'

    resources :ticket_type_groups, path: 'grupos_tipo_de_senha' do
      resources :ticket_types,     path: 'tipos_de_senha'
    end

    resources :places, path: 'localidades' do

      get 'home', path: 'lista_de_guiches'

      resources :tickets, path: 'senhas'

      resources :reports, path: 'relatorios', only: :index do
        get 'tickets_per_day',                  path: 'senhas_por_dia',                      on: :collection
        get 'tickets_per_month',                path: 'senhas_por_mes',                      on: :collection
        get 'attendances_by_days_per_wicket',   path: 'atendimentos_por_dia_por_guiche',     on: :collection
        get 'attendances_by_wickets_per_day',   path: 'atendimentos_por_guiche_por_dia',     on: :collection
        get 'attendances_by_wickets_per_month', path: 'atendimentos_por_guiche_por_mes',     on: :collection
        get 'waiting_time_by_wicket',           path: 'tempo_de_espera_por_guiche',          on: :collection
        get 'waiting_time_by_day_per_wicket',   path: 'tempo_de_espera_por_dia_por_guiche',  on: :collection
        get 'waiting_time_by_wicket_per_month', path: 'tempo_de_espera_por_guiche_por_mes',  on: :collection
        get 'waiting_time_by_client',           path: 'tempo_de_espera_por_cliente',         on: :collection
        get 'waiting_time_by_client_per_month', path: 'tempo_de_espera_por_cliente_por_mes', on: :collection
        get 'waiting_time_by_month_per_wicket', path: 'tempo_de_espera_por_mes_por_guiche',  on: :collection
        get 'attendances_by_month_per_wicket',  path: 'atendimentos_por_mes_por_guiche',     on: :collection
      end

      resources :panels, path: 'paineis' do
        get 'tickets',   path: 'senhas'
      end

      resources :wickets,     path: 'guiches' do
        get 'tickets',        path: 'senhas'
        get 'call_next',      path: 'chamar_proximo'
        get 'call_ticket',    path: 'chamar_senha'
        put 'recall',         path: 'rechamar'
        put 'attend',         path: 'atender'
        put 'put_waiting',    path: 'por_em_espera'
        put 'back_available', path: 'tornar_disponivel'
        put 'examine',        path: 'examinar'
        delete 'cancel',      path: 'cancelar'
      end

      resources :totems do
        get 'ticket_type_groups', path: 'grupos_tipo_senha'
        get 'generate_ticket',    path: 'gerar_senha'

        resources :ticket_type_groups do
          get 'generate_ticket', path: 'gerar_senha'
        end
      end

    end
  end

  match 'main' => "home#main", as: "main"
  match 'localidades' => "places#home", as: "home"
  match 'logout' => "session#logout"
  root to: 'home#index'

end

app/models/report.rb
class Report
  
  attr_accessor :first, :second, :query
  attr_reader :error, :valid, :results
  
  def self.queries(*args) 
    args.each do |query| 
      instance_eval do 
        define_singleton_method query do |first, second|
          new( first , second,  query)
        end 
      end
    end
  end    

  queries :tickets_per_day, :waiting_time_by_client, :waiting_time_by_wicket, :attendances_by_wickets_per_day,
          :tickets_per_month, :waiting_time_by_wicket_per_month, :attendances_by_wickets_per_month, 
          :attendances_by_days_per_wicket, :waiting_time_by_day_per_wicket, :waiting_time_by_month_per_wicket, 
          :waiting_time_by_client_per_month, :attendances_by_month_per_wicket

  def valid?
    @valid = valid_range_of_dates? && results? 
  end

  def to(place)
    @place = (place.is_a? Place) ? place.id : place
    self
  end

  def filtered_by(wickets)
    @wicket_ids = wickets unless wickets.nil? || wickets.empty?
    self
  end
    
  private

  def initialize(first, second, query)
    @first, @second, @query = first, second, query
  end
  
  def tickets_per_day(start_date, end_date)
    Ticket.select("to_char(trunc(created_at), 'dd/MM/yyyy' ) as date_local, count(id) as count_id")
         .where(:created_at => start_date.midnight..end_date.tomorrow.midnight)
         .where(:place_id => @place)
         .group("trunc(created_at)")
         .order("trunc(created_at) DESC")
  end

  def attendances_by_wickets_per_day(start_date, end_date)
    
    result = query_attendance_wicket(start_date, end_date)
    var_return = {}

    result.each do |r|
      var_return[r.value.to_sym] ||= {}
      (var_return[r.value.to_sym][:values] ||= []) << r.count_id
      (var_return[r.value.to_sym][:dates] ||= []) << r.date_local
    end

    var_return.to_a
  end
  
  def attendances_by_days_per_wicket(start_date, end_date)
    result = query_attendance_wicket(start_date, end_date)

    var_return = {}

    result.each do |r|
      var_return[r.date_local.to_sym] ||= {}
      (var_return[r.date_local.to_sym][:wickets] ||= [])  << r.value
      (var_return[r.date_local.to_sym][:values] ||= [])   << r.count_id
    end

    var_return.to_a
    
  end
  
  def query_attendance_wicket(start_date, end_date)
    
    filter = @wicket_ids ? { "wickets.id" => @wicket_ids } : ""

    call_histories = CallHistory.select("to_char(trunc(call_histories.created_at), 'dd/MM/yyyy' ) as date_local, wickets.value, count('call_histories.id') as count_id")
           .joins(:wicket)
           .where(  
             :created_at => start_date.midnight..end_date.tomorrow.midnight,
             :status_ticket_id => StatusTicket.attended.id,
             "wickets.place_id" => @place
           )
           .where(filter)
           .group("trunc(call_histories.created_at), wickets.value")
           .order("trunc(call_histories.created_at) DESC, wickets.value ASC")
  end
  
  def waiting_time_by_wicket(start_date, end_date)

    results = query_waiting_time_by(start_date, end_date)
    
    var_return = {}
    
    results.each do |call|
      (var_return[call.wicket_name.to_sym] ||= [])  << call
    end

    var_return.to_a
  end
  
  def waiting_time_by_day_per_wicket(start_date, end_date)

    results = query_waiting_time_by(start_date, end_date)
    
    var_return = {}
    
    results.each do |r|
      (var_return[r.data.to_sym] ||= [])  << r
    end

    var_return.to_a
  end
  
  def query_waiting_time_by(start_date, end_date)
    called_table = <<-SQL
      (SELECT call_histories.wicket_id, call_histories.ticket_id, max(call_histories.created_at) as created
         FROM call_histories
         WHERE call_histories.status_ticket_id = #{StatusTicket.called.id}
         GROUP BY call_histories.ticket_id, call_histories.wicket_id
         ORDER BY call_histories.wicket_id, call_histories.ticket_id) called
    SQL

    attended_table = <<-SQL
      (SELECT call_histories.wicket_id, call_histories.ticket_id, max(call_histories.created_at) as created
         FROM call_histories
         WHERE call_histories.status_ticket_id = #{StatusTicket.attended.id}
         GROUP BY call_histories.ticket_id, call_histories.wicket_id
         ORDER BY call_histories.wicket_id, call_histories.ticket_id) attended
    SQL

    select = <<-SQL
      called.wicket_id, wickets.value as wicket_name , to_char(trunc(called.created), 'dd/MM/yyyy') as data , count(called.ticket_id) as total , avg(attended.created-called.created) * 24 * 60 as time
    SQL
      where = <<-SQL
      attended.wicket_id = called.wicket_id
      and attended.ticket_id = called.ticket_id
      and attended.wicket_id = wickets.id
      and called.wicket_id = wickets.id
    SQL

    filter = @wicket_ids ? { "wickets.id" => @wicket_ids } : ""

    results = Wicket.select(select)
        .from(" wickets, #{attended_table}, #{called_table} ")
        .where(where)
        .where(filter)
        .where("called.created" => start_date.midnight..end_date.tomorrow.midnight)
        .where(:place_id => @place)
        .group("called.wicket_id, wickets.value, trunc(called.created)")
        .order("called.wicket_id, wickets.value, trunc(called.created) DESC")
    
  end
  
  def waiting_time_by_client(start_date, end_date)
    attended_table = <<-SQL
      (SELECT call_histories.wicket_id, call_histories.ticket_id, max(call_histories.created_at) as created
         FROM call_histories
         WHERE call_histories.status_ticket_id = #{StatusTicket.attended.id}
         GROUP BY call_histories.ticket_id, call_histories.wicket_id
         ORDER BY call_histories.wicket_id, call_histories.ticket_id) attended
    SQL
    
    select = <<-SQL 
      to_char(trunc(t.created_at), 'dd/MM/yyyy') as data, count(attended.ticket_id) as total, avg(attended.created - t.created_at) * 24 * 60 as time
    SQL
    
    filter = @wicket_ids ? { "attended.wicket_id" => @wicket_ids } : ""
    
    CallHistory.select(select)  
               .from("tickets t, #{attended_table}")
               .where("attended.ticket_id = t.id")
               .where(filter)
               .where("t.created_at" => start_date.midnight..end_date.tomorrow.midnight, 
                      "t.place_id" => @place)
               .group("trunc(t.created_at)")
               .order("trunc(t.created_at)")
  end

  def attendances_by_wickets_per_month(start_date, end_date)
    
    results = query_attendance_by_wicket(start_date, end_date)
    
    var_return = {}

    results.each do | r |
      var_return[r.value.to_sym] ||= {}
      (var_return[r.value.to_sym][:values] ||=[])  << r.count_id
      (var_return[r.value.to_sym][:dates] ||=[] ) << r.date_local
    end

    var_return.to_a
    
  end
  
  def attendances_by_month_per_wicket(start_date, end_date)
    
      results = query_attendance_by_wicket(start_date, end_date)

      var_return = {}

      results.each do | r |
        var_return[r.date_local.to_sym] ||= {}
        (var_return[r.date_local.to_sym][:values] ||=[])  << r.count_id
        (var_return[r.date_local.to_sym][:dates] ||=[] ) << r.value
      end

      var_return.to_a
    
  end
  
  def query_attendance_by_wicket(start_date, end_date)

    format = "{%Y, %m, %d}"
    start  = Date.strptime("{#{start_date[:year]}, #{start_date[:month]}, 01}", format)
    finish = Date.strptime("{#{end_date[:year]}, #{end_date[:month]}, 01}", format)

    filter = @wicket_ids ? { "wickets.id" => @wicket_ids } : ""

    call_histories = CallHistory.select("wickets.value, to_char(trunc(call_histories.created_at), 'MM/yyyy') as date_local, count('call_histories.id') as count_id")
          .joins(:wicket)
          .where(filter)
          .where(
            :created_at => start..finish.end_of_month.tomorrow,
            :status_ticket_id => StatusTicket.attended.id,
            "wickets.place_id" => @place
          )
          .group("wickets.value, to_char(trunc(call_histories.created_at), 'MM/yyyy')")
          .order("wickets.value ASC, to_char(trunc(call_histories.created_at), 'MM/yyyy') DESC")    
  end
  
  def waiting_time_by_month_per_wicket(start_date, end_date)
    
    results = query_waiting_time_by_wicket_month(start_date, end_date)

    var_return = {}

    results.each do |call|
      (var_return[call.data.to_sym] ||= []) << call
    end

    var_return.to_a
  end
  
  def waiting_time_by_wicket_per_month(start_date, end_date)
  
    results = query_waiting_time_by_wicket_month(start_date, end_date)

    var_return = {}
   
    results.each do |call|
      (var_return[call.wicket_name.to_sym] ||= []) << call
    end
   
    var_return.to_a     
    
  end
  
  def query_waiting_time_by_wicket_month(start_date, end_date)
    
    format = "{%Y, %m, %d}"
    start  = Date.strptime("{#{start_date[:year]}, #{start_date[:month]}, 01}", format)
    finish = Date.strptime("{#{end_date[:year]}, #{end_date[:month]}, 01}", format)

    called_table = <<-SQL
      (SELECT call_histories.wicket_id, call_histories.ticket_id, max(call_histories.created_at) as created
         FROM call_histories
         WHERE call_histories.status_ticket_id = #{StatusTicket.called.id}
         GROUP BY call_histories.ticket_id, call_histories.wicket_id
         ORDER BY call_histories.wicket_id, call_histories.ticket_id) called
    SQL

    attended_table = <<-SQL
      (SELECT call_histories.wicket_id, call_histories.ticket_id, max(call_histories.created_at) as created
         FROM call_histories
         WHERE call_histories.status_ticket_id = #{StatusTicket.attended.id}
         GROUP BY call_histories.ticket_id, call_histories.wicket_id
         ORDER BY call_histories.wicket_id, call_histories.ticket_id) attended
    SQL

    select = <<-SQL
      called.wicket_id, wickets.value as wicket_name , to_char(trunc(called.created), 'MM/yyyy') as data , count(called.ticket_id) as total , avg(attended.created-called.created) * 24 * 60 as time
    SQL

    where = <<-SQL
      attended.wicket_id = called.wicket_id

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  prawnto :filename => "#{DateTime.now.to_i}.pdf", :inline => false

  def index
    @place = Place.find(params[:place_id])
  end

  def tickets_per_day
    filter_date
    @report = Report.tickets_per_day(@first_date, @second_date).to(@place)
    handle_result @report, :tickets_per_day
  end

  def attendances_by_wickets_per_day
    filter_date
    @report = Report.attendances_by_wickets_per_day(@first_date, @second_date)
                    .to(@place)
                    .filtered_by(@wicket_ids)
    handle_result @report, :attendances_per_day
  end
  
  def tickets_per_month
    filter_place
    @report = Report.tickets_per_month(params[:start_date], params[:end_date]).to(@place)
    handle_result  @report,  :tickets_per_month 
  end 

  def attendances_by_wickets_per_month
    filter_wicket
    @report = Report.attendances_by_wickets_per_month(params[:start_date], params[:end_date])
                    .to(@place)
                    .filtered_by(@wicket_ids)
    handle_result @report, :attendances_per_month
  end

  def attendances_by_month_per_wicket
    filter_wicket
    @report = Report.attendances_by_month_per_wicket(params[:start_date], params[:end_date])
                    .to(@place)
                    .filtered_by(@wicket_ids)
    handle_result @report, :attendances_per_month
  end

  def attendances_by_days_per_wicket
    filter_date
    @report = Report.attendances_by_days_per_wicket(@first_date, @second_date)
                    .to(@place)
                    .filtered_by(@wicket_ids)
    handle_result @report, :attendances_per_wicket
  end
 
  def waiting_time_by_client 
    filter_date
    @report = Report.waiting_time_by_client(@first_date, @second_date)
                    .to(@place)
                    .filtered_by(@wicket_ids)
    handle_result @report, :waiting_time_by_client
  end
 
  def waiting_time_by_client_per_month
    filter_wicket
    @report = Report.waiting_time_by_client_per_month(params[:start_date], params[:end_date])
                    .to(@place)
                    .filtered_by(@wicket_ids)
    handle_result @report, :waiting_time_clients_per_month
  end
  
  def waiting_time_by_wicket
    filter_date
    @report = Report.waiting_time_by_wicket(@first_date, @second_date).to(@place).filtered_by(@wicket_ids)
    handle_result @report, :waiting_time_by_wicket  
  end
 
  def waiting_time_by_wicket_per_month
    filter_wicket
    @report = Report.waiting_time_by_wicket_per_month(params[:start_date], params[:end_date])
                    .to(@place)
                    .filtered_by(@wicket_ids)
    handle_result @report, :wickets_per_month
  end

  def waiting_time_by_month_per_wicket
    filter_wicket
    @report = Report.waiting_time_by_month_per_wicket(params[:start_date], params[:end_date])
                    .to(@place)
                    .filtered_by(@wicket_ids)
    handle_result @report, :wickets_per_month
  end

  def waiting_time_by_day_per_wicket
    filter_date
    @report = Report.waiting_time_by_day_per_wicket(@first_date, @second_date).to(@place).filtered_by(@wicket_ids)
    handle_result @report, :waiting_time_by_wicket  
  end

  private 
   
  def handle_result(report, result) 
    respond_to do |format|
      if report.valid?
        instance_variable_set("@#{result}", report.results)
        format.html
        format.json { render :json => instance_variable_get("@#{result}") }
        format.pdf { render :layout => false }
      else
        format.html {render :notice => I18n.t('application.no_results')}
        format.json {render :json => nil}
      end
    end    
  end
  
  def filter_place
    @place = Place.find(params[:place_id])
  end
  
  def filter_date
    filter_place
    @first_date = params[:start_date] && params[:start_date].to_date 
    @second_date = params[:end_date] && params[:end_date].to_date
    filter_wicket
  end
  
  def filter_wicket
    filter_place
    @wickets = @place.wickets
    @wicket_ids = params[:wicket][:ids] unless params[:wicket].nil?
  end
    
end

app/views/reports/attendances_by_days_per_wicket.html.erb
<%= stylesheet_link_tag 'jquery-ui-1.8.15.custom', 'tipsy' %>
<div class="form">
  <div class="place-spot"><%= @place.value %></div>
  <h1 class="spotlight"><%= t('application.reports.attendances_by_days_per_wicket.name') %></h1>
  <div class="search" style="width:95%; margin-bottom: 30px">
    <%= form_tag( attendances_by_wickets_per_day_place_reports_path, :method => "get" ) do %>
      <div style="float: right;">
        <%= submit_tag( t('application.search'), :class => "button medium" ) %>
      </div>
      <div style="float: right;">
        <%= label_tag t('application.reports.since') %>
        <%= text_field_tag :start_date, nil, :class => "date from", :readonly => true %>
        <%= label_tag t('application.reports.to') %>
        <%= text_field_tag :end_date, nil, :class => "date to", :readonly => true %>
      </div>
      <% if @wickets %>
        <div style="float: right; width: 90%">
          <%= label_tag t('model.wicket.name') %>:
          <% @wickets.each do |wicket| %>
            <%= (truncate wicket.value, :length => 9, :omission => '') %>
            <%= check_box_tag "wicket[ids][]", wicket.id %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div id="graph" class="graph"></div>
  <% unless @attendances_per_wicket.nil? || @attendances_per_wicket.empty? %>
    <table>
      <tr>
        <th style="text-align: center;"><%= t('application.reports.attendances_by_days_per_wicket.date') %></th>
        <th style="text-align: center;"><%= t('activerecord.models.wicket') %></th>
        <th style="text-align: center;"><%= t('application.reports.attendances_by_days_per_wicket.quantity') %></th>
      </tr>
      <% total= 0 %>
      <% length= 0 %>
      <% @attendances_per_wicket.each do |call_history| %>
	<% length += call_history[1].values[0].size %>
        <% current_date = call_history[0].to_s.to_date %>
        <tr>
          <td width="180px" style="text-align: center; background-color : white" rowspan="<%= call_history[1].values[0].size + 1 %>"><%= l(current_date, :format => :default) %> (<%=l(current_date, :format => '%A') %>)</td>
        </tr>
        <% call_history[1].values[1].each_with_index do |val, index| %>
          <tr>
            <td width="40%" style="text-align: center;"><%= call_history[1][:wickets][index] %></td>
            <td width="40%" style="text-align: center;"><%= val %></td>
          </tr>
          <% total += val.to_i %>
        <% end %>
      <% end %>
        <tr>
          <td colspan="2" style="text-align: right;"><%= t('application.reports.average') %></td>
          <td style="text-align: center;"><%= total / length %></td>
        </tr>
        <tr>
          <td colspan="2" style="text-align: right;"><%= t('application.reports.total') %></td>
          <td style="text-align: center;"><%= total %></td>
        </tr>
    </table>
    <div class="print">
      <%= link_to t('application.reports.print'), attendances_by_days_per_wicket_place_reports_path( :start_date => params[:start_date], :end_date => params[:end_date], :wicket => params[:wicket], :format => 'pdf' ), :class => "button medium" %>
    </div>
  <% end %>
  <div style="width:95%; margin-bottom: 30px; padding-top: 20px; margin-left: 10px">
    <%= link_to t('model.back'), place_reports_path(@place.id), :class => "button medium"%>
  </div>
  <%= javascript_include_tag 'protovis', 'report_attendances_by_days_per_wicket', 'jquery.tipsy', 'report', 'tipsy' %>
  <script type='text/javascript'>
    renderProtovis(<%= @attendances_per_wicket.to_json.html_safe %>);
  </script>
</div>

app/views/reports/attendances_by_month_per_wicket.html.erb
<%= stylesheet_link_tag 'jquery-ui-1.8.15.custom', 'tipsy' %>
<div class="form">
  <div class="place-spot"><%= @place.value %></div>
  <h1 class="spotlight"><%= t('application.reports.attendances_by_month_per_wicket.name') %></h1>
  <div class="search" style="width:95%; margin-bottom: 30px">
    <%= form_tag( attendances_by_month_per_wicket_place_reports_path, :method => "get" ) do %>
	  <div class="select-date">
            <div style="float: right;">
	      <%= submit_tag( t('application.search'), :class => "button medium" ) %>
            </div>
            <div style="float: right;">
      	      <%= label_tag t('application.reports.since') %>
	      <%= select_date(nil, :prefix => "start_date", :discard_day => true, :prompt => {:month => t('application.reports.chose.month'), :year => t('application.reports.chose.year')}) %>
	      <%= label_tag t('application.reports.to') %>
	      <%= select_date(nil, :prefix => "end_date", :discard_day => true, :prompt => {:month => t('application.reports.chose.month'), :year => t('application.reports.chose.year')}) %>
            </div>
            <% if @wickets %>
              <div style="float: right;">
      	        <%= label_tag t('model.wicket.name') %>:
                <% @wickets.each do |wicket| %>
                  <%= (truncate wicket.value, :length => 9, :omission => '') %>
                  <%= check_box_tag "wicket[ids][]", wicket.id %>
                <% end %>
              </div>
            <% end %>
	  </div>
    <% end %>
  </div>
  <div id="graph" class="graph"></div>
  <% unless @attendances_per_month.nil? || @attendances_per_month.empty? %>
    <table>
      <tr>
        <th style="text-align: center;"><%= t('activerecord.models.wicket') %></th>
        <th style="text-align: center;"><%= t('application.reports.attendances_by_month_per_wicket.month_year') %></th>
        <th style="text-align: center;"><%= t('application.reports.attendances_by_month_per_wicket.quantity') %></th>
      </tr>
      <% total= 0 %>
      <% length= 0 %>
      <% @attendances_per_month.each do |call_history| %>
		<% length += call_history[1].values[0].size %>
        <tr>
          <td width="180px" style="text-align: center; background-color : white" rowspan="<%=call_history[1].values[0].size + 1 %>"><%= unabbreviated_month_year(call_history[0])%></td>
        </tr>
        <% call_history[1].values[0].each_with_index do |val, index| %>
          <tr>
            <td width="40%" style="text-align: center;"><%= call_history[1][:dates][index] %> </td>
            <td width="40%" style="text-align: center;"><%= val %></td>
          </tr>
          <% total += val %>
        <% end %>
      <% end %>
        <tr>
          <td colspan="2" style="text-align: right;"><%= t('application.reports.average') %></td>
          <td style="text-align: center;"><%= total / length %></td>
        </tr>
        <tr>
          <td colspan="2" style="text-align: right;"><%= t('application.reports.total') %></td>
          <td style="text-align: center;"><%= total %></td>
        </tr>
    </table>
    <div class="print">
      <%= link_to t('application.reports.print'), attendances_by_month_per_wicket_place_reports_path( :start_date => params[:start_date], :end_date => params[:end_date], :wicket => params[:wicket], :format => 'pdf' ), :class => "button medium" %>
    </div>
  <% end %>
  <div style="width:95%; margin-bottom: 30px; padding-top: 20px; margin-left: 10px">
    <%= link_to t('model.back'), place_reports_path(@place.id), :class => "button medium"%>
  </div>
  <%= javascript_include_tag 'protovis', 'attendances_by_wickets', 'jquery.tipsy', 'report', 'tipsy' %>
  <script type='text/javascript'>
    renderProtovis(<%= @attendances_per_month.to_json.html_safe %>);
  </script>
</div>

app/views/reports/index.html.erb
<div class="form">
  <div class="place-spot">
    <%= @place.value %>
  </div>
  <div class="search">
    <input type="text" value="search" id="search"/>
    <%= link_to image_tag("form/search.png") + t('application.search') , "#", :class => "button medium"%>
  </div>
  <table>
    <tr>
      <th><%= t('application.reports.name').pluralize %></th>
      <th class="options"><%= t("application.options") %></th>
    </tr>
    <tr class="row">
      <td width ="100%"><%= t('application.reports.tickets_per_day.name') %></td>
      <td><%= link_to image_tag("form/search.gif"), tickets_per_day_place_reports_path, :title => t('model.show') %></td>
    </tr>
    <tr class="row">
      <td><%= t('application.reports.attendances_by_wickets_per_day.name') %></td>
      <td><%= link_to image_tag("form/search.gif"), attendances_by_wickets_per_day_place_reports_path, :title => t('model.show') %></td>
    </tr>

    <tr class="row">
      <td><%= t('application.reports.waiting_time_by_wicket.name') %></td>
      <td><%= link_to image_tag("form/search.gif"), waiting_time_by_wicket_place_reports_path, :title => t('model.show') %></td>
    </tr>

    <tr class="row">
      <td><%= t('application.reports.waiting_time_by_client.name') %></td>
      <td><%= link_to image_tag("form/search.gif"), waiting_time_by_client_place_reports_path, :title => t('model.show') %></td>
    </tr>

    <tr class="row">
      <td width ="100%"><%= t('application.reports.tickets_per_month.name') %></td>
      <td><%= link_to image_tag("form/search.gif"), tickets_per_month_place_reports_path, :title => t('model.show') %></td>
    </tr>

    <tr class="row">
      <td width ="100%"><%= t('application.reports.attendances_by_wickets_per_month.name') %></td>
      <td><%= link_to image_tag("form/search.gif"), attendances_by_wickets_per_month_place_reports_path, :title => t('model.show') %></td>
    </tr>

     <tr class="row">
      <td width ="100%"><%= t('application.reports.waiting_time_by_wicket_per_month.name') %></td>
      <td><%= link_to image_tag("form/search.gif"), waiting_time_by_wicket_per_month_place_reports_path, :title => t('model.show') %></td>
    </tr>

    <tr class="row">
      <td><%= t('application.reports.attendances_by_days_per_wicket.name') %></td>
      <td><%= link_to image_tag("form/search.gif"), attendances_by_days_per_wicket_place_reports_path, :title => t('model.show') %></td>
    </tr>

    <tr class="row">
      <td><%= t('application.reports.waiting_time_by_day_per_wicket.name') %></td>
      <td><%= link_to image_tag("form/search.gif"), waiting_time_by_day_per_wicket_place_reports_path, :title => t('model.show') %></td>
    </tr>

    <tr class="row">
      <td><%= t('application.reports.waiting_time_by_client_per_month.name') %></td>
      <td><%= link_to image_tag("form/search.gif"), waiting_time_by_client_per_month_place_reports_path, :title => t('model.show') %></td>
    </tr>

    <tr class="row">
      <td><%= t('application.reports.waiting_time_by_month_per_wicket.name') %></td>
      <td><%= link_to image_tag("form/search.gif"), waiting_time_by_month_per_wicket_place_reports_path, :title => t('model.show') %></td>
    </tr>

    <tr class="row">
      <td><%= t('application.reports.attendances_by_month_per_wicket.name') %></td>
      <td><%= link_to image_tag("form/search.gif"), attendances_by_month_per_wicket_place_reports_path, :title => t('model.show') %></td>
    </tr>
 </table>
</div>