config/routes.rb
Ticketer::Application.routes.draw do

  scope(path_names: { new: 'novo', show: 'visualizar', edit: 'editar' } ) do

    resources :locals,         path: 'locais'
    resources :call_histories, path: 'historico_de_chamadas'
    resources :guidances,      path: 'orientacoes'
    resources :tickets,        path: 'senhas'
    resources :statuses,       path: 'status'
    resources :status_tickets, path: 'status_de_senha'
    resources :printers,       path: 'impressoras'

    resources :ticket_type_groups, path: 'grupos_tipo_de_senha' do
      resources :ticket_types,     path: 'tipos_de_senha'
    end

    resources :places, path: 'localidades' do

      get 'home', path: 'lista_de_guiches'

      resources :tickets, path: 'senhas'

      resources :reports, path: 'relatorios', only: :index do
        get 'tickets_per_day',                  path: 'senhas_por_dia',                      on: :collection
        get 'tickets_per_month',                path: 'senhas_por_mes',                      on: :collection
        get 'attendances_by_days_per_wicket',   path: 'atendimentos_por_dia_por_guiche',     on: :collection
        get 'attendances_by_wickets_per_day',   path: 'atendimentos_por_guiche_por_dia',     on: :collection
        get 'attendances_by_wickets_per_month', path: 'atendimentos_por_guiche_por_mes',     on: :collection
        get 'waiting_time_by_wicket',           path: 'tempo_de_espera_por_guiche',          on: :collection
        get 'waiting_time_by_day_per_wicket',   path: 'tempo_de_espera_por_dia_por_guiche',  on: :collection
        get 'waiting_time_by_wicket_per_month', path: 'tempo_de_espera_por_guiche_por_mes',  on: :collection
        get 'waiting_time_by_client',           path: 'tempo_de_espera_por_cliente',         on: :collection
        get 'waiting_time_by_client_per_month', path: 'tempo_de_espera_por_cliente_por_mes', on: :collection
        get 'waiting_time_by_month_per_wicket', path: 'tempo_de_espera_por_mes_por_guiche',  on: :collection
        get 'attendances_by_month_per_wicket',  path: 'atendimentos_por_mes_por_guiche',     on: :collection
      end

      resources :panels, path: 'paineis' do
        get 'tickets',   path: 'senhas'
      end

      resources :wickets,     path: 'guiches' do
        get 'tickets',        path: 'senhas'
        get 'call_next',      path: 'chamar_proximo'
        get 'call_ticket',    path: 'chamar_senha'
        put 'recall',         path: 'rechamar'
        put 'attend',         path: 'atender'
        put 'put_waiting',    path: 'por_em_espera'
        put 'back_available', path: 'tornar_disponivel'
        put 'examine',        path: 'examinar'
        delete 'cancel',      path: 'cancelar'
      end

      resources :totems do
        get 'ticket_type_groups', path: 'grupos_tipo_senha'
        get 'generate_ticket',    path: 'gerar_senha'

        resources :ticket_type_groups do
          get 'generate_ticket', path: 'gerar_senha'
        end
      end

    end
  end

  match 'main' => "home#main", as: "main"
  match 'localidades' => "places#home", as: "home"
  match 'logout' => "session#logout"
  root to: 'home#index'

end

app/models/place.rb
class Place < ActiveRecord::Base
  extend FriendlyId
  
  friendly_id :value, use: :slugged
  
  #String :value
  #String :user
  #Integer :status
  #Integer :local

  attr_accessible :value, :ticket_type_group_tokens, :ticket_type_group_ids, 
                  :local_id, :sequential_by_type_group, :status, :status_id
  attr_reader :ticket_type_group_tokens

  belongs_to :status
  belongs_to :local
  has_many :wickets
  has_many :tickets
  has_many :panels
  has_many :totems
  has_and_belongs_to_many :ticket_type_groups, :uniq => :true

  validates :value, :status, :local, :user, :ticket_type_groups, :presence => true

  accepts_nested_attributes_for :totems, :tickets, :wickets, :panels

  def tickets_called(ticket_type_groups= []) 
    calleds = nil

    unless ticket_type_groups.empty?
      calleds = tickets.includes(:ticket_type)
        .where("ticket_types.ticket_type_group_id" => ticket_type_groups)
        .where(:status_ticket_id => StatusTicket.called.id)
    end

    calleds ||= tickets.where(:status_ticket_id => StatusTicket.called.id)

    calleds
  end

  def tickets_availables(ticket_type_groups= [])
    availables = nil

    unless ticket_type_groups.empty?
      availables = tickets.includes(:ticket_type)
        .where("ticket_types.ticket_type_group_id" => ticket_type_groups)
        .where(:status_ticket_id => StatusTicket.available.id)
    end

    availables ||= tickets.where(:status_ticket_id => StatusTicket.available.id)

    availables
  end

  def tickets_attended(ticket_type_groups= [])
    attended = nil

    unless ticket_type_groups.empty?
      attended = tickets.includes(:ticket_type)
        .where("ticket_types.ticket_type_group_id" => ticket_type_groups)
        .where(:status_ticket_id => StatusTicket.attended.id)
    end

    attended ||= tickets.where(:status_ticket_id => StatusTicket.attended.id)

    attended
  end
  
  def ticket_type_group_tokens=(tokens)
    self.ticket_type_group_ids = TicketTypeGroup.ids_from_tokens(tokens)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    @places = Place.order(:value)
    respond_with(@places)
  end

  def show
    @place = Place.find(params[:id])
    @locals = Local.all
    @ticket_type_groups = TicketTypeGroup.order(:value)
    @statuses = Status.order(:value)
    respond_with(@places)
  end

  def new
    @place = Place.new( :status => Status.active )
    @locals = Local.all
    @ticket_type_groups = TicketTypeGroup.order(:value)
    @statuses = Status.order(:value)
    respond_with(@places)
  end

  def edit
    @place = Place.find(params[:id])
    @locals = Local.all
    @ticket_type_groups = TicketTypeGroup.order(:value)
    @statuses = Status.order(:value)
  end

  def create
    @place = Place.new(params[:place])
    @place.user= "user test"
    @locals = Local.all
    flash[:notice] = "Place was successfully created." if @place.save
    respond_with(@place)
  end

  def update
    @place = Place.find(params[:id])
    @locals = Local.all
    flash[:notice] = "Place was successfully updated." if @place.update_attributes(params[:place])
    respond_with(@place)
  end

  def home
    @place = Place.find(params[:place_id])
    @wickets = @place.wickets.where(:status_id => Status.active.id).order(:value)
    render :layout => 'places'
  end
end

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @place.errors.full_messages.each do |msg| %>
        <li class="form-msg-error"><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="grid-12-12">
    <%= f.label :value, :class => "form-lbl form-req"%>
    <%= f.text_field :value, :class => "form-txt form-small", :disabled => disabled %>
  </div>

  <div class="grid-12-12">
    <%= f.label :local, :class => "form-lbl form-req" %>
    <% if @place && @place.local_id && disabled %>
      <input type="text" value="<%= @place.local.des_local %>" disabled="disabled" class="form-txt form-small" />
    <% elsif %>
      <%= f.collection_select( :local_id, @locals, :id, :des_local, { :prompt => true }, :class => "form-small", :disabled => disabled  ) %>
    <% end %>
  </div>

  <div class="grid-12-12">
    <%= f.label :ticket_type_group_tokens, :class => "form-lbl form-req" %>
    <ul>
      <li>
        <%= f.text_field :ticket_type_group_tokens, data: { load: @place.ticket_type_groups }, :class => "form-txt form-small", :disabled => disabled %>
      </li>
    </ul>
  </div>

  <div class="grid-12-12">
    <%= f.label :sequential_by_type_group, :class => "form-lbl form-req"%>
    <ul class="form-list-rdo">
      <li>
        <%= f.radio_button :sequential_by_type_group, "true", :disabled => disabled  %>
        <%= f.label t('model.place.sequential_by_type_group.sure'), :class => "form-lbl" %>
      </li>
      <li>
        <%= f.radio_button :sequential_by_type_group, "false", :disabled => disabled  %>
        <%= f.label t('model.place.sequential_by_type_group.not'), :class => "form-lbl"%>
      </li>
    </ul>
  </div>

  <div class="grid-12-12">
    <%= f.label :status, :class => "form-lbl form-req"%>
    <ul class="form-list-rdo">
      <% @statuses.each do |status| %>
        <li>
          <%= f.radio_button :status_id, status.id , :disabled => disabled  %>
          <%= f.label status.value, :class => "form-lbl" %>
        </li>
      <% end %>
    </ul>
  </div>

  <% unless disabled %>
    <div class="grid-7-12 field-button field-clear">
      <%= f.submit :class => "button form-right medium" %>
    </div>
  <%end%>
<% end %>

app/views/places/edit.html.erb
<div class="form">
  <fieldset>
    <legend><%= t('model.place.editing') %></legend>
    <%= render :partial => 'form', :locals => {:disabled => false } %>
  </fieldset>
</div>
<div class="buttons-nav">
  <%= link_to t('model.show'), @place , :class => "button medium"%> 
  <%= link_to t('model.back'), places_path , :class => "button medium"%>
</div>

app/views/places/home.html.erb
<div style="position:relative; top: -40px">
  <div class="place-spot">
    <%= @place.value %><br/><br/>
	<%= link_to image_tag("report.gif", :width => "44px", :style =>"vertical-align:middle") + "  #{t('application.reports.plural')}", place_reports_path(params[:place_id]), :style => "padding:0;font-size:20px" %>

  </div>
  <% @wickets.each do |wicket| %>
    <div style="width : 184px; heigth: 200px; float: left">
      <%= link_to image_tag("computer.png", :width => "184px"), place_wicket_tickets_path(wicket.place, wicket), :style => "padding:0"  %>
      <h3 style="text-align: center"><%= wicket.value %></h3>
    </div>
  <% end %>
  <div style="clear:both"></div>
</div>

app/views/places/index.html.erb
<div class="form">
  <div class="search">
    <input type="text" value="search" id="search"/>
    <%= link_to image_tag("form/search.png") + t('application.search') , "#", :class => "button medium"%>
  </div>
  <table>
    <tr>
      <th><%= t('model.place.name').pluralize %></th>
      <th><%= t('model.place.sequential_by_type_group.name') %></th>
      <th><%= t('model.status.name') %></th>
      <th colspan="5" class="options"><%= t("application.options") %></th>
    </tr>
    <% @places.each do |place| %>
      <tr class="row">
        <td width="60%"><%= place.value %></td>
        <td width="20%"><%= place.sequential_by_type_group ? t('model.place.sequential_by_type_group.sure') : t('model.place.sequential_by_type_group.not') %></td>
        <td width="20%"><%= place.active? ? t('model.status.active') : t('model.status.inactive') %></td>
        <td><%= link_to image_tag("form/search.gif"), place, :title => t('model.show') %></td>
        <td><%= link_to image_tag("form/edit.gif"), edit_place_path(place), :title => t('model.edit') %></td>
        <td><%= link_to image_tag("form/totem.gif"), place_totems_path(place), :title => t('model.totem.name') %></td>
        <td><%= link_to image_tag("form/wicket.gif"), place_wickets_path(place), :title => t('model.wicket.name') %></td>
        <td><%= link_to image_tag("form/panel.gif"), place_panels_path(place), :title => t('model.panel.name') %></td>
      </tr>
    <% end %>
  </table>
</div>
<div class="buttons-nav">
  <%= link_to t('model.place.new'), new_place_path, :class => "button medium" %>
</div>

app/views/places/new.html.erb
<div class="form">
  <fieldset>
    <legend><%= t('model.place.new') %></legend>
    <%= render :partial => 'form', :locals => {:disabled => false } %>
  </fieldset>
</div>
<div class="buttons-nav">
  <%= link_to t('model.back'), places_path, :class => "button medium"  %>
</div>

app/views/places/show.html.erb
<div class="form">
  <fieldset>
    <legend><%= t('model.place.name') %></legend>
    <% if notice %>
      <span class="form-msg-success"><%= notice %></span>
    <% end %>
    <%= render :partial => 'form', :locals => {:disabled => true } %>
  </fieldset>
</div>
<div class="buttons-nav">
  <%= link_to t('model.edit'), edit_place_path(@place), :class => "button medium"%> 
  <%= link_to t('model.back'), places_path, :class => "button medium" %>
</div>